services:
  Grafana:
      image: horna-home-lab/grafana
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: ${GRAFANA_CONTAINER_NAME}
      hostname: ${GRAFANA_HOSTNAME}
      restart: unless-stopped
      environment:
        TZ: ${SYSTEM_TIME_ZONE}
        GF_DATE_FORMATS_DEFAULT_TIMEZONE: ${SYSTEM_TIME_ZONE}
      volumes:
        - ./datasources:/etc/grafana/provisioning/datasources
        - ./dashboards_provisioning:/etc/grafana/provisioning/dashboards
        - ./dashboards:/var/lib/grafana/dashboards
        - ${APP_DATA_PATH}:/var/lib/grafana
        - ${APP_LOG_PATH}:/var/log/grafana
      ports:
        - ${GRAFANA_EXTERNAL_PORT}:3000
      healthcheck:
        test: curl --fail http://${GRAFANA_IP}:3000/api/health
        start_period: 2s
        interval: 3s
        timeout: 1s
        retries: 5