name: Create tag

on:
  workflow_call:
    inputs:
      version_tag:
        type: string
        required: true
      tag_reference_exist:
        type: string
        required: true

jobs:
  Create_Version_Tag:
    runs-on: container
    steps:
      - name: Create Tag ${{ inputs.version_tag }} object
        if: ${{ inputs.tag_reference_exist == 'false' }}
        run: |
          curl -L -s --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${{ github.repository }}/git/tags \
            -d '{ 
              "tag":"${{ inputs.version_tag }}", 
              "message":"tag from container", 
              "object":"${{ github.sha }}", 
              "type":"commit"
            }'

      - name: Create Tag ${{ inputs.version_tag }} reference
        if: ${{ inputs.tag_reference_exist == 'false' }}
        run: |
          curl -L -s --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${{ github.repository }}/git/refs \
            -d '{
              "ref":"refs/tags/${{ inputs.version_tag }}",
              "sha":"${{ github.sha }}"
            }'

      - name: Update Tag ${{ inputs.version_tag }} reference
        if: ${{ inputs.tag_reference_exist == 'true' }}
        run: |
          curl -L -s --fail-with-body \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${{ inputs.version_tag }} \
            -d '{ 
              "sha":"${{ github.sha }}",
              "force":true
            }'