on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: development
        options:
          - development
          - production

permissions: write-all


jobs:
  get_runners:
    uses: HornaHomeLab/depl_dev/.github/workflows/Check_runner.yaml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      inherit

  deploy:
    uses: HornaHomeLab/depl_dev/.github/workflows/Deploy_version.yaml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      inherit