on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: development
        options:
          - development
          - production

  push:


jobs:
  Up:
    uses: HornaHomeLab/depl_dev/.github/workflows/Check_runner.yaml@main
    with:
      environment: "development"
    secrets:
      inherit

  Deployment:
    needs: Up
    uses: HornaHomeLab/depl_dev/.github/workflows/Deploy_version.yaml@main
    with:
      environment: "development"
    secrets:
      inherit