name: Deploy
run-name: Deploy to ${{inputs.environment}}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: development
        options:
          - development
          - production

  push:


jobs:
  Deployment:
    uses: HornaHomeLab/depl_dev/.github/workflows/Deploy_docker_compose.yml@main
    with:
      environment: "development"
    secrets:
      inherit