name: Deploy
run-name: Deploy to ${{inputs.environment}}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: development
        options:
          - development
          - production

  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        default: development


jobs:
  Deployment:
    uses: HornaHomeLab/Actions_Deployments/.github/workflows/Run_docker_compose.yml@main
    with:
      environment: "development"
    secrets:
      inherit