on:
  workflow_dispatch:

permissions: write-all


jobs:
  get_runners:
    runs-on: container
    steps:
      - name: call api
        run: | 
          curl -L -s --fail-with-body \ 
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_RUNNERS_MGMT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/HornaHomeLab/actions/runners