on:
  workflow_call:
    inputs:
      environment_type:
        type: string
        required: true
      

jobs:
  Get_Version_Tag:
    uses: HornaHomeLab/Learn_GH_Features/.github/workflows/Check_if_tag_exist.yaml@main

  Create_Version_Tag:
    runs-on: container
    needs: Get_Version_Tag
    steps:
      - name: Create Tag ${{ needs.Get_Version_Tag.outputs.version_tag }} object
        run: |
          echo "${{ needs.Get_Version_Tag.outputs.version_tag }}"
          curl -L -s --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${{ github.repository }}/git/tags \
            -d '{ 
              "tag":"${{ needs.Get_Version_Tag.outputs.version_tag }}", 
              "message":"tag from container", 
              "object":"${{ github.sha }}", 
              "type":"commit"
            }'
      - name: Create Tag ${{ needs.Get_Version_Tag.outputs.version_tag }} reference
        run: |
          curl -L -s --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --url https://api.github.com/repos/${{ github.repository }}/git/refs \
            -d '{
              "ref":"refs/tags/${{ needs.Get_Version_Tag.outputs.version_tag }}",
              "sha":"${{ github.sha }}"
            }'
