name: Release

on:
  pull_request:
    types: [ opened, closed ]

permissions:
  contents: write

jobs:
  Create_Pre_Release:
      if: github.event.pull_request.merged == false
      uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_create_release.yaml@main
      with:
        pre_release: true
        archive_name: "test"
        files: "./README.md "

  Create_Release:
    if: github.event.pull_request.merged == true
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_create_release.yaml@main
    with:
      pre_release: false
      archive_name: "test"
      files: "./README.md "
