name: PR

on:
  pull_request:

permissions:
  contents: write

jobs:
  Test:
    runs-on: container
    steps:
      - name: Print ${{github.event.action}}
        run : echo "${{github.event.action}}"

  Create_Pre_Release:
      if: github.event.pull_request.merged == false && (github.event.action == 'opened' || github.event.action == 'edited')
      uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_create_release.yaml@main
      with:
        pre_release: true
        archive_name: "test"
        files: "./README.md "

  Create_Release:
    if: github.event.pull_request.merged == true && github.event.action == 'closed'
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_create_release.yaml@main
    with:
      pre_release: false
      archive_name: "test"
      files: "./README.md "

      
  Remove_Release:
    if: github.event.pull_request.merged == false && github.event.action == 'closed'
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_remove_release.yaml@addRemovalWorkflows