on:
  workflow_dispatch:

  push:

permissions:
  contents: write

jobs:
  Trigger_Workflow:
      uses: HornaHomeLab/Learn_GH_Features/.github/workflows/Process_create_release.yaml@main
      with:
        archive_name: "test"
        files: "./workflowHelpers/get-version.sh ./README.md ./t"
    