name: PR

on:
  pull_request:
    types: [ opened, synchronize, closed ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  Create_Pre_Release:
      if: github.event.pull_request.merged == false && (github.event.action == 'opened' || github.event.action == 'synchronize')
      uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_create_release.yaml@main
      with:
        pre_release: true
        archive_name: "test"
        files: "./README.md "

  Create_Release:
    if: github.event.pull_request.merged == true && github.event.action == 'closed'
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_create_release.yaml@main
    with:
      pre_release: false
      archive_name: "test"
      files: "./README.md "

  Deploy:
    needs: Create_Release
    if: github.event.pull_request.merged == true && github.event.action == 'closed'
    uses: HornaHomeLab/Learn_GH_Features/./github/workflows/Check_runner.yaml@main
    with:
      environment: "development"

      
  Remove_Release:
    if: github.event.pull_request.merged == false && github.event.action == 'closed'
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_remove_release.yaml@main