name: Release

on:
  pull_request:
    types: [opened, synchronize, closed]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  Pre:
    if: github.event.pull_request.merged == false && (github.event.action == 'opened' || github.event.action == 'synchronize')
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_create_release.yml@development
    with:
      pre_release: true
      archive_name: "test"


  Full:
    if: github.event.pull_request.merged == true && github.event.action == 'closed'
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_create_release.yml@development
    with:
      pre_release: false
      archive_name: "test"


  Deploy:
    needs: Full
    uses: HornaHomeLab/Actions_Deployments/.github/workflows/Run_docker_compose.yml@main
    with:
      environment: "development"
    secrets: inherit


  # Remove:
  #   if: github.event.pull_request.merged == false && github.event.action == 'closed'
  #   uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_remove_release.yaml@main
