name: Publish release
run-name: Publish release ${{ github.repository }}

on:
  workflow_call:
    inputs:
      environment_type:
        type: string
        required: true
      files:
        type: string
        default: "./workflowHelpers/get-version.sh ./README.md ./t"

jobs:
  Get_Version:
    uses: HornaHomeLab/Learn_GH_Features/.github/workflows/Check_version.yaml@main

  Create_Tag:
    needs: Get_Version
    uses: HornaHomeLab/Learn_GH_Features/.github/workflows/Create_tag.yaml@main
    with:
      version_tag: ${{ needs.Get_Version.outputs.version_tag }}
      tag_reference_exist: ${{ needs.Get_Version.outputs.tag_reference_exist }}

  Create_Release:
    needs: [Get_Version, Create_Tag]
    uses: HornaHomeLab/Learn_GH_Features/.github/workflows/Create_release.yaml@main
    with:
      version_tag: ${{ needs.Get_Version.outputs.version_tag }}
      pre_release: 'false'

  Upload_Assets:
    needs: [Get_Version, Create_Release]
    uses: HornaHomeLab/Learn_GH_Features/.github/workflows/Update_asset.yaml@main
    with:
      archive_name: "test_archive"
      release_id: ${{ needs.Create_Release.outputs.release_id }}
      version_tag: ${{ needs.Get_Version.outputs.version_tag }}
      files_to_archive: ${{ inputs.files }}