on:
  workflow_dispatch:
    inputs:
      environment_type:
        description: Select the environment
        type: choice
        default: "DEV"
        required: true
        options:
          - DEV
          - PROD

jobs:
  test:
    runs-on: container
    steps:
      - name: test powershell
        id: a
        shell: pwsh
        run: |
          $a = 123
          $b = "acb"
          $c = "$a-$b"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "my_var=$c"
      - name: read va
        shell: pwsh
        run: |
          write-host "${{steps.a.outputs.my_var}}"
